name: parallel_demo

jobs:
  lint:
    steps:
      - name: lint the code
        run: echo "linting..."

  unit_tests:
    steps:
      - name: run unit tests
        run: echo "running unit tests..."

  deploy:
    needs: [lint, unit_tests]
    steps:
      - name: deploy
        run: echo "deploying..."
